import type { ImportOptions } from '@/lib/engine/types';

/**
 * The bundled sample datasets.
 *
 * Two related tables rather than one, deliberately: a single file can only
 * demonstrate filtering and grouping, whereas a pair lets the first five minutes
 * cover a join — which is the thing people actually open a workbench for.
 *
 * They're served from this app's own origin, so "try the sample data" doesn't
 * break the promise that nothing leaves the browser. Generated by
 * `scripts/make-samples.mjs`, with a few nulls, a duplicate key and some
 * unmatched foreign keys left in on purpose.
 */
export interface SampleDataset {
  table: string;
  path: string;
  filename: string;
  description: string;
  options: ImportOptions;
}

export const SAMPLE_DATASETS: SampleDataset[] = [
  {
    table: 'orders',
    path: '/samples/orders.csv',
    filename: 'orders.csv',
    description: '1,500 orders over 18 months — dates, regions, categories, quantities, prices.',
    options: { table: 'orders', format: 'csv', delimiter: ',', hasHeader: true },
  },
  {
    table: 'customers',
    path: '/samples/customers.csv',
    filename: 'customers.csv',
    description: '201 customers with country, segment and signup date — joins to orders.',
    options: { table: 'customers', format: 'csv', delimiter: ',', hasHeader: true },
  },
];

/** A starter query worth having open on first run. */
export const SAMPLE_QUERY = `-- Revenue by region and category, biggest first.
-- Press Cmd/Ctrl+Enter to run it, then open the Chart tab below.
SELECT
  region,
  category,
  round(sum(quantity * unit_price), 2) AS revenue
FROM orders
WHERE quantity > 0
GROUP BY region, category
ORDER BY revenue DESC;`;

export async function fetchSample(sample: SampleDataset): Promise<File> {
  const response = await fetch(sample.path);
  if (!response.ok) throw new Error(`Could not load ${sample.filename}`);
  return new File([await response.blob()], sample.filename, { type: 'text/csv' });
}
